services:
  database:
    image: 'postgres:17-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ash_use_cases_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dev/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements

volumes:
  postgres_data:
