defmodule AshUseCases.Repo.Migrations.AddSimpleresources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:simple_resources, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :name, :text, null: false
      add :private_comment, :text
      add :count, :bigint
    end
  end

  def down do
    drop table(:simple_resources)
  end
end
